# Generated by Django 5.2.13 on 2026-05-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cateegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_blog.cateegory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
