# Generated by Django 5.2.13 on 2026-05-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0010_cateegory_alter_article_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Cateegory',
        ),
    ]
